{
 "title": "CloudNotes Dashboard",
 "tags": [
  "cloudnotes",
  "devops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "job", "query": "label_values(up, job)" }
  ]
 },
 "panels": [
  {
   "title": "Request Rate (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=~\"$job\"}[5m]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "API Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{job=~\"$job\"}[5m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Total Notes Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(notes_created_total{job=~\"$job\"})",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Total Notes Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(notes_updated_total{job=~\"$job\"})",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Total Notes Deleted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(notes_deleted_total{job=~\"$job\"})",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "Backend Status"
    }
   ]
  }
 ]
}