FROM jenkins/jenkins:lts-jdk21
USER root
RUN apt-get update && apt-get install -y curl
# Install plugins on build
RUN jenkins-plugin-cli --plugins "git github workflow-aggregator docker-workflow credentials-binding configuration-as-code job-dsl matrix-auth ssh-agent"
# Disable setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

USER jenkins
