FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y curl
# Install plugins on build
RUN jenkins-plugin-cli --plugins "git workflow-aggregator docker-workflow credentials-binding configuration-as-code"
# Disable setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY jenkins.yaml /var/jenkins_home/jenkins.yaml
ENV CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml

USER jenkins
