jenkins:
  systemMessage: "CloudNotes Automated CI/CD Pipeline"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "CHANGE_ME"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

unclassified:
  location:
    url: "http://REPLACE_ME_JENKINS_IP:8080/"

jobs:
  - script: >
      pipelineJob('CloudNotes-Pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/savinaysingh7/cloudnotes.git')
                }
                branches('main')
              }
            }
          }
        }
      }
